### ISSUE TITLE
PasswordPolicyControl ambiguous graceAuthNsRemaining

### ISSUE THREAD

**Issue by dfish3r** [vt-middleware/ldaptive#131]
The PasswordPolicyControl implementation defaults graceAuthNsRemaining to zero.
Per the RFC, zero is a valid value and could be returned by the server.
The client has no way to determine if the server sent the value zero or no value at all.

See https://groups.google.com/forum/#!topic/ldaptive/nzj62B_Z2js

**Comment by marwatk** [comment]
If it helps, the apache api handles this case in two ways:

- The default values for both are -1 and are only set if present
- The controls object itself isn't returned if there is no warning

**Comment by dfish3r** [comment]
I reviewed the behavior against OpenLDAP ppolicy and got the following results:
```
successful bind graceAuthNsRemaining=2
successful bind graceAuthNsRemaining=1
failed bind error=PASSWORD_EXPIRED
```
So the behavior is certainly different than ApacheDS.
Could you put ldaptive logging in TRACE and perform a test against ApacheDS?
Step down grace logins until you get a failed bind and look for logs of the form: `decoding control: `
Post that output to this issue.

**Comment by dfish3r** [comment]
Pushed a potential fix to 1.2.4-SNAPSHOT
I'd still like to get some TRACE data for what ApacheDS is actually sending for the control.

**Comment by marwatk** [comment]
Working on getting trace data, I'll see if I can get that today. We swapped out for using org.apache in our code for now so I have to swap it back.

My reading of 8.1.2.3.2 in the rfc leads me to think the final error should be invalid credentials, with the password policy also showing password expired as informational aside. But the invalid credentials is much more important to see, because in that state it is not possible for the user to change the password anymore, so seeing the expired password message is more of a red herring because it can't be fixed like a normal expired password.

After grace auths are used, only a password reset is allowed to change the password, not a modify using the existing password (since the user can no longer bind to perform the password change).

**Comment by marwatk** [comment]
Here are the results of the trace:
```
decoding control: MAWgA4EBAg==
produced response controls: [[org.ldaptive.control.PasswordPolicyControl@-350057145::criticality=false, timeBeforeExpiration=0, graceAuthNsRemaining=2, error=null]]
decoding control: MAWgA4EBAQ==
produced response controls: [[org.ldaptive.control.PasswordPolicyControl@-350057258::criticality=false, timeBeforeExpiration=0, graceAuthNsRemaining=1, error=null]]
decoding control: MAWgA4EBAA==
produced response controls: [[org.ldaptive.control.PasswordPolicyControl@-350057371::criticality=false, timeBeforeExpiration=0, graceAuthNsRemaining=0, error=null]]
decoding control: MAOBAQA=
produced response controls: [[org.ldaptive.control.PasswordPolicyControl@1125954332::criticality=false, timeBeforeExpiration=0, graceAuthNsRemaining=0, error=PASSWORD_EXPIRED]]
```

**Comment by marwatk** [comment]
Reading through your commit I think it'll mitigate the issue. A consumer can use the -1 values to determine if values were specified by the server.

Though it feels a little wrong to have to test for a special value. Maybe methods like isTimeBeforeExpirationPresent() and isGraceAuthsRemainingPresent()? That feels weird too, though. Ideally you'd hand back nullable objects, but that would break existing stuff. I guess I don't really have good solution, so maybe the special -1 is ideal in this case.

**Comment by dfish3r** [comment]
Thanks for the report and test data, that should close this out.
